name: SampleFlow CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pushd .
        cd $HOME
        sudo apt-get install -y doxygen graphviz libboost-all-dev numdiff clang libc++-dev libc++abi-dev libeigen3-dev ninja-build
        doxygen --version
        popd
    - name: cmake-gcc
      run: |
           mkdir build-gcc
           cd build-gcc
           cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: ctest-gcc
      run: |
           cd build-gcc
           ctest --output-on-failure -j2
    - name: cmake-clang
      run: |
           mkdir build-clang
           cd build-clang
           export CXX=clang++
           cmake -DCMAKE_BUILD_TYPE=Debug -GNinja ..
    - name: ctest-clang
      run: |
           cd build-clang
           ninja
           ctest --output-on-failure -j2
    - name: doc
      run: |
           cd build-gcc
           make doc
    - name: style
      run: |
        wget -O astyle_2.04_linux.tar.gz https://sourceforge.net/projects/astyle/files/astyle/astyle%202.04/astyle_2.04_linux.tar.gz/download
        tar -xvf astyle_2.04_linux.tar.gz
        cd astyle/build/gcc && make && sudo make install
        cd ../../..
        ./doc/indent
        git --no-pager diff --exit-code
