name: SampleFlow CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo apt-get install doxygen graphviz libboost-all-dev numdiff -y
        doxygen --version
    - name: cmake
      run: cmake .
    - name: ctest
      run: ctest -j8
