name: SampleFlow CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pushd .
        cd $HOME
        sudo apt-get install doxygen graphviz libboost-all-dev numdiff -y
        doxygen --version
        git clone https://gitlab.com/libeigen/eigen.git
        mkdir ./eigen-build
        mkdir ./eigen-install
        cd ./eigen-build
        cmake ../eigen -DCMAKE_INSTALL_PREFIX=$HOME/eigen-install
        make install
        popd
    - name: cmake
      run: cmake -DEIGEN_DIR="$HOME/eigen-install" .
    - name: ctest
      run: ctest --output-on-failure -j2
    - name: doc
      run: make doc
    - name: style
      run: |
        wget -O astyle_2.04_linux.tar.gz https://sourceforge.net/projects/astyle/files/astyle/astyle%202.04/astyle_2.04_linux.tar.gz/download
        tar -xvf astyle_2.04_linux.tar.gz
        cd astyle/build/gcc && make && sudo make install
        cd ../../..
        ./doc/indent
        git --no-pager diff --exit-code
